common/urls.py
from __future__ import absolute_import

from django.conf.urls import url, include
from common.views import (Commands,
                          CommandExecuteList, CommandExecuteDetailApi,
                          CredentialCreate, CredentialList, CredentialDetailApi,
                          ServerCreate, ServerlList, GroupList, GroupCreate,
                          LogList, CommandLogList, WebterminalHelperDetectApi, WebterminalHelperDetectCallbackApi, PasswordResetView,
                          PasswordResetDoneView, PasswordResetConfirmView,
                          SettingsView, SettingsOtpView,
                          )
from common.api import ServerGroupViewSet, ServerInforViewSet, CommandsSequenceViewSet, CredentialViewSet
from rest_framework import routers
from django.contrib import admin
from django.views.decorators.csrf import csrf_exempt
from common.admin import OTPAdminSite
admin.site.__class__ = OTPAdminSite
from .views import (CommandsFilterList, CommandsFilterDetailApi, CommandsFilter, AssignProfileToUserList, AssignProfileToUserDetailApi, AssignProfileToUser,
TimeSlotview, TimeSlotList, TimeSlotDetailApi)
from .api import AssignFilterViewSet, FilterCommandsViewSet, UserViewSet
# Register webterminal api
router = routers.DefaultRouter()
router.register('servergroup', ServerGroupViewSet)
router.register('serverinfo', ServerInforViewSet)
router.register('commandssequence', CommandsSequenceViewSet)
router.register('credential', CredentialViewSet)
router.register('assignfilter', AssignFilterViewSet)
router.register('filterCommands', FilterCommandsViewSet)
router.register('user', UserViewSet)


urlpatterns = [
    url(r'^commands/add/$', Commands.as_view(), name='commandscreate'),
    url(r'^commandslist/$', CommandExecuteList.as_view(), name='commandslist'),
    url(r'^commandsapi/$', CommandExecuteDetailApi.as_view(), name='commandsapi'),
    url(r'^credentialcreate/$', CredentialCreate.as_view(),
        name='credentialcreate'),
    url(r'^credentiallist/$', CredentialList.as_view(), name='credentiallist'),
    url(r'^credentialdetailapi/$', CredentialDetailApi.as_view(),
        name='credentialdetailapi'),
    url(r'^servercreate/$', ServerCreate.as_view(), name='servercreate'),
    url(r'^serverlist/$', ServerlList.as_view(), name='serverlist'),
    url(r'^groupcreate/$', GroupCreate.as_view(), name='groupcreate'),
    url(r'^grouplist/$', GroupList.as_view(), name='grouplist'),
    url(r'^logslist/$', LogList.as_view(), name='logslist'),
    url(r'^commandsloglist/$', CommandLogList.as_view(), name='commandsloglist'),
    url(r'^api/', include(router.urls)),
    url(r'^webterminalhelperdetect/$', WebterminalHelperDetectApi.as_view(),
        name='webterminalhelperdetectapi'),
    url(r'^webterminalhelperdetectcallback/$', csrf_exempt(WebterminalHelperDetectCallbackApi.as_view()),
        name='webterminalhelperdetectcallbackapi'),
    url(r"password-reset/$", PasswordResetView.as_view(), name="password-reset"),
    url(
        r"password-reset-done/",
        PasswordResetDoneView.as_view(),
        name="password-reset-done",
    ),
    url(
        r"^password-reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$",
        PasswordResetConfirmView.as_view(),
        name="password-reset-confirm",
    ),
    url(r"settings/$", SettingsView.as_view(), name="settings"),
    url(r"settings-otp/$", SettingsOtpView.as_view(), name="settings-otp"),

    url(r'^filtercommands/add/$', CommandsFilter.as_view(), name='filtercommandscreate'),
    url(r'^filtercommands/$', CommandsFilterList.as_view(), name='filtercommandslist'),
    url(r'^filtercommandsapi/$', CommandsFilterDetailApi.as_view(), name='filtercommandsapi'),

    url(r'^assignProfiletouser/$', AssignProfileToUserList.as_view(), name='assignProfiletouserlist'),
    url(r'^assignProfiletouser/add/$', AssignProfileToUser.as_view(), name='assignProfiletouserlistcreate'),
    url(r'^assignProfiletouserapi/$', AssignProfileToUserDetailApi.as_view(), name='assignProfiletouserlistapi'),

    url(r'^timeslot/$', TimeSlotList.as_view(), name='timeslotlist'),
    url(r'^timeslot/add/$', TimeSlotview.as_view(), name='timeslotcreate'),
    url(r'^timeslotapi/$', TimeSlotDetailApi.as_view(), name='timeslotapi'),
]

permission/urls.py
from django.conf.urls import url

from permission.views import UserRegister, UserUpdate, UserList, UserDelete, PermissionCreate, PermissionList, PermissionUpdate, PermissionDelete

urlpatterns = [
    url(r'^user/add/$', UserRegister.as_view(), name='usercreate'),
    url(r'^user/(?P<pk>[0-9]+)/update/$',
        UserUpdate.as_view(), name='userupdate'),
    url(r'^user/(?P<pk>[0-9]+)/delete/$',
        UserDelete.as_view(), name='userdelete'),
    url(r'^user/$', UserList.as_view(), name='userlist'),
    url(r'^permission/$', PermissionList.as_view(), name='permissionlist'),
    url(r'^permission/add/$', PermissionCreate.as_view(), name='permissioncreate'),
    url(r'^permission/(?P<pk>[0-9]+)/update/$',
        PermissionUpdate.as_view(), name='permissionupdate'),
    url(r'^permission/(?P<pk>[0-9]+)/delete/$',
        PermissionDelete.as_view(), name='permissiondelete'),
]

webterminal/urls.py
from __future__ import absolute_import
from django.conf.urls import url, include
from django.contrib import admin
from webterminal.views import Index, SshLogPlay, SshTerminalKill, SshTerminalMonitor, CommandExecute, BatchCommandExecute, SshConnect, DynamicPassword
from django.contrib.auth.views import LoginView, LogoutView
from django.views.static import serve
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^guacamole/', include('guacamole.urls')),
    url(r'^$', Index.as_view(), name='index'),
    url(r'^sshconnect/(?P<ip>(?:(?:0|1[\d]{0,2}|2(?:[0-4]\d?|5[0-5]?|[6-9])?|[3-9]\d?)\.){3}(?:0|1[\d]{0,2}|2(?:[0-4]\d?|5[0-5]?|[6-9])?|[3-9]\d?))/(?P<serverid>[0-9]+)/$',
        SshConnect.as_view(), name='sshconnect'),
    url(r'^commandexecute/$', CommandExecute.as_view(), name='commandexecute'),
    url(r'^batchcommandexecute/$', BatchCommandExecute.as_view(),
        name='batchcommandexecute'),
    url(r'^sshterminalkill/$', SshTerminalKill.as_view(), name='sshterminalkill'),
    url(r'^sshlogplay/(?P<pk>[0-9]+)/',
        SshLogPlay.as_view(), name='sshlogplay'),
    url(r'^sshterminalmonitor/(?P<pk>[0-9]+)/',
        SshTerminalMonitor.as_view(), name='sshterminalmonitor'),
    url(r'^accounts/login/$',
        LoginView.as_view(template_name='admin/login.html'), name='login'),
    url(r'^accounts/logout/$',
        LogoutView.as_view(template_name='registration/logged_out.html'), name='logout'),
    url(r'^elfinder/', include('elfinder.urls')),
    url(r'^permission/', include('permission.urls')),
    url(r'^common/', include('common.urls')),
    url(r'^i18n/', include('django.conf.urls.i18n')),
    url(r'^dynamicpassword/$', DynamicPassword.as_view(), name='dynamicpassword'),
]


if settings.DEBUG:
    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += [
        url(r'^media/(?P<path>.*)$', serve,
            {'document_root': settings.MEDIA_ROOT, }),
    ]

permission/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from common.models import ServerGroup
from django.contrib.auth.models import User
from django.contrib.auth.models import Permission as AuthPermission
from django.contrib.contenttypes.models import ContentType
from django.utils.translation import ugettext_lazy as _


class Permission(models.Model):
    user = models.OneToOneField(User, verbose_name=_(
        'User'), related_name='permissionuser', on_delete=models.CASCADE)
    permissions = models.ManyToManyField(
        AuthPermission, verbose_name=_('Permissions'), related_name='permission')
    groups = models.ManyToManyField(
        ServerGroup, verbose_name=_('Server group'))
    createdatetime = models.DateTimeField(
        auto_now_add=True, verbose_name=_('Create time'))
    updatedatetime = models.DateTimeField(
        auto_created=True, auto_now=True, verbose_name=_('Update time'))

    def __unicode__(self):
        return self.user.username

    def __str__(self):
        return self.user.username

    class Meta:
        permissions = (
            ("can_add_user", _("Can add user")),
            ("can_change_user", _("Can change user info")),
            ("can_delete_user", _("Can delete user info")),
            ("can_view_user", _("Can view user info")),
            ("can_view_permissions", _("Can view user permissions")),
            ("can_change_permissions", _("Can change user permissions")),
            ("can_delete_permissions", _("Can revoke user permissions")),
            ("can_add_permissions", _("Can add user permissions")),
        )


class Role(models.Model):
    name = models.CharField(max_length=50, verbose_name=_(
        'Role name'), blank=False, unique=True)
    permissions = models.ManyToManyField(
        AuthPermission, verbose_name=_('Permissions'), related_name='rolepermission', limit_choices_to={'content_type__app_label__in': ['common', 'permission'], "codename__contains": 'can_'})
    groups = models.ManyToManyField(
        ServerGroup, verbose_name=_('Server group'))
    createdatetime = models.DateTimeField(
        auto_now_add=True, verbose_name=_('Create time'))
    updatedatetime = models.DateTimeField(
        auto_created=True, auto_now=True, verbose_name=_('Update time'))

    def __unicode__(self):
        return self.user.username

    def __str__(self):
        return self.user.username

    class Meta:
        permissions = (
            ("can_add_role", _("Can add role")),
            ("can_change_role", _("Can change role info")),
            ("can_delete_role", _("Can delete role info")),
            ("can_view_role", _("Can view role info")),
            ("can_view_role_permissions", _("Can view role permissions")),
            ("can_change_role_permissions", _("Can change role permissions")),
            ("can_delete_role_permissions", _("Can revoke role permissions")),
            ("can_add_role_permissions", _("Can add role permissions")),
        )

permission/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.models import Permission as AuthPermission
from permission.models import Permission
from django.contrib.contenttypes.models import ContentType
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Div, Field
from django.db import models
from django.forms.widgets import CheckboxSelectMultiple
from django.utils.encoding import force_text
from django.utils.translation import ugettext_lazy as _


class RegisterForm(forms.Form):

    def __init__(self, *args, **kwargs):
        self.helper = FormHelper()
        self.helper.form_class = 'form-horizontal'
        self.helper.label_class = 'col-md-2'
        self.helper.field_class = 'col-md-8'
        self.helper.layout = Layout(*[Div(field, css_class='form-group')
                                      for field in ['user', 'newpassword1', 'newpassword2', 'email']])
        self.instance = False
        if 'instance' in kwargs.keys():
            kwargs.pop('instance')
            self.instance = True
        super(RegisterForm, self).__init__(*args, **kwargs)

    user = forms.CharField(
        required=True,
        label=_(u"user name"),
        error_messages={'required': _(u'Please input a valid user.')},
        max_length=100,
        widget=forms.TextInput(
            attrs={
                'class': u"form-control",
            }
        )
    )
    newpassword1 = forms.CharField(
        required=True,
        label=_(u"your password"),
        error_messages={'required': _(u'Please input your password')},
        widget=forms.PasswordInput(
            attrs={
                'placeholder': _(u"new password"),
                'class': u"form-control",
            }
        )
    )
    newpassword2 = forms.CharField(
        required=True,
        label=_(u"verify your password"),
        error_messages={'required': _(u'please input your  password again')},
        widget=forms.PasswordInput(
            attrs={
                'placeholder': _(u"verify your password"),
                'class': u"form-control",
            }
        )
    )
    email = forms.EmailField(
        required=True,
        label=_(u"email"),
        error_messages={'required': _(
            u'Please input a valid email address.')},
        widget=forms.EmailInput(
            attrs={
                'class': u"form-control",
            }
        )
    )

    def clean(self):
        if not self.is_valid():
            raise forms.ValidationError({'user': _(u"every filed required")})
        elif self.cleaned_data['newpassword1'] != self.cleaned_data['newpassword2']:
            raise forms.ValidationError({'newpassword1': _(
                u"your password does't the same"), 'newpassword2': _(u"your password does't the same")})
        elif self.cleaned_data['user']:
            if not self.instance:
                if User.objects.filter(username=self.cleaned_data['user']):
                    raise forms.ValidationError(
                        {'user': _(u"User name has been registered!")})
        cleaned_data = super(RegisterForm, self).clean()
        return cleaned_data


class CustomModelMultipleChoiceField(forms.ModelMultipleChoiceField):
    def label_from_instance(self, obj):
        return force_text(_(obj.name))


class PermissionForm(forms.ModelForm):
    permissions = CustomModelMultipleChoiceField(queryset=AuthPermission.objects.
                                                 filter(content_type__app_label__in=[
                                                        'common', 'permission'], codename__contains='can_'),
                                                 widget=forms.CheckboxSelectMultiple())

    def __init__(self, *args, **kwargs):
        super(PermissionForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_class = 'form-horizontal'
        self.helper.label_class = 'col-md-2'
        self.helper.field_class = 'col-md-8'
        self.helper.layout = Layout(*[Div(field, css_class='form-group')
                                      for field in ['user', 'permissions', 'groups']])

    class Meta:
        model = Permission
        fields = ['user', 'permissions', 'groups']

permission/templates/permission/permissioncreate.html
{% extends 'base.html'%}
{%load i18n%}
{% block title %}{{ title }}{% endblock %}
{% load staticfiles %}
{% block css %}
<link rel="stylesheet" href="{% static 'plugins/select2/dist/css/select2.min.css' %}">
<link rel="stylesheet" href="{% static 'plugins/select2-bootstrap-theme/dist/select2-bootstrap.min.css' %}">
<link rel="stylesheet" href="{% static 'plugins/jstree/themes/proton/style.min.css' %}"/>
{% endblock %}
{% block content %}
{% load crispy_forms_tags %}
<section class="content">
    <div class="row">
        <div class="col-md-12">
            <!-- BEGIN EXAMPLE TABLE PORTLET-->
            <div class="box box-success">
                <div class="box-header with-border">
                    <div class="caption">
                        <button class="btn btn-primary" onclick="window.location.href = '{% url 'permissionlist' %}'">
                            {%trans 'Return Permission List' %}
                        </button>
                    </div>

                    <div class="box-tools pull-right">
                        <button type="button" class="btn btn-box-tool" data-widget="collapse"><i
                                class="fa fa-minus"></i>
                        </button>
                        <div class="btn-group">
                            <button type="button" class="btn btn-box-tool dropdown-toggle" data-toggle="dropdown">
                                <i class="fa fa-wrench"></i></button>
                            <ul class="dropdown-menu" role="menu">
                                <li><a href="#">{%trans 'Action' %}</a></li>
                                <li><a href="#">{%trans 'Another action' %}</a></li>
                                <li><a href="#">{%trans 'Something else here' %}</a></li>
                                <li class="divider"></li>
                                <li><a href="#">{%trans 'Separated link' %}</a></li>
                            </ul>
                        </div>
                        <button type="button" class="btn btn-box-tool" data-widget="remove"><i class="fa fa-times"></i>
                        </button>
                    </div>
                </div>

                <form id="id-m-form" action="" method="post" class="form form-horizontal " role="form">
                    <div class="box-body">
                        {% if form.helper %}
                            {% crispy form form.helper %}
                        {% else %}
                            {% crispy form %}
                        {% endif %}
                        <div class="form-group">
                            <div id="div_id_permissions_tree" class="form-group"><label for="div_id_permissions_tree"
                                                                            class="control-label col-md-2 requiredField">
                                {%trans 'Permissions' %}<span class="asteriskField">*</span> </label>
                                <div class="controls col-md-8">

                                 </div>
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-xs-offset-2 col-xs-10">
                                <button type="submit" class="btn btn-primary">{%trans 'submit' %}</button>
                                <button type="button" class="btn btn-default goback" onclick="history.back()">{%trans 'cancel' %}</button>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
            <!-- END EXAMPLE TABLE PORTLET-->
        </div>

    </div>
</section>
{% endblock %}
{% block js %}
<script type="text/javascript" src="{% static 'plugins/select2/dist/js/select2.full.min.js' %}"></script>
<script src="{% static 'plugins/jstree/jstree.js' %}"></script>
<script type="application/javascript">
    $('#id_groups,#id_user').select2({
        theme: "bootstrap"
    });
    //hide original permission tree
    $(".form-group[id='div_id_permissions']").hide()

    //generate new permission tree
    $("#div_id_permissions_tree >.col-md-8").jstree({
        core: {
            themes: {
                name: 'proton',
                // responsive: true
            },
            responsive: true,
            check_callback: 0,
            data: {{permission_tree_list|safe}},
        },
        types: {
            default: {icon: "fa fa-folder icon-state-warning icon-lg"},
            file: {icon: "fa fa-file icon-state-warning icon-lg"}
        },
        plugins: ["types","checkbox","state"],
        checkbox: {
            "tie_selection": false,
            "whole_node": false
        },
    }).on("check_node.jstree", function (e, data) {
            //update form data when select tree node
            if (data.node.original.level == "three"){
                $("input[value='"+data.node.original.id+"']").prop("checked",true)
            }else if (data.node.original.level == "two"){
                $(data.node.children).each(function (index,item) {
                    $("input[value='"+item+"']").prop("checked",true)
                })
            }else{
                $(data.node.children_d).each(function (index,item) {
                    $("input[value='"+item+"']").prop("checked",true)
                })
            }
        }).on("uncheck_node.jstree", function (e, data) {
        if (data.node.original.level == "three"){
            $("input[value='"+data.node.original.id+"']").prop("checked",false)
        }else if (data.node.original.level == "two"){
            $(data.node.children).each(function (index,item) {
                $("input[value='"+item+"']").prop("checked",false)
            })
        }else{
            $(data.node.children_d).each(function (index,item) {
                $("input[value='"+item+"']").prop("checked",false)
            })
        }
    }).on("loaded.jstree", function (event, data) {
        //initial tree data
        setTimeout(function () {
            $("#div_id_permissions_tree >.col-md-8").jstree(true).uncheck_all();
        },50)
        setTimeout(function () {
            $("#div_id_permissions_tree >.col-md-8 a").removeClass("jstree-clicked")
            $("#div_id_permissions >.col-md-8 .checkbox >label >input:checked").each(function (index, item) {
                $(this).prop("checked",false)
            });
        },100)
    });

    //remove initial data
    $("#div_id_permissions >.col-md-8 .checkbox >label >input:checked").each(function (index, item) {
        $(this).prop("checked",false)
    });
</script>
<script>
  $("[href='{% url 'permissionlist' %}']").parent("li").addClass('active')
</script>
{% endblock %}

permission/templates/permission/permissiondelete.html
{% extends 'base.html'%}
{%load i18n%}
{% block title %}{%trans 'Permission delete' %}{% endblock %}
{% load staticfiles %}
{% block content %}
<section class="content">
    <div class="row">
        <div class="col-md-12">
            <!-- BEGIN EXAMPLE TABLE PORTLET-->
            <div class="box box-success">
                <div class="box-header with-border">
                    <div class="caption">
                        <button class="btn btn-primary" onclick="window.location.href = '{% url 'permissionlist' %}'">
                            {% trans 'Return Permission list' %}
                        </button>
                    </div>

                    <div class="box-tools pull-right">
                        <button type="button" class="btn btn-box-tool" data-widget="collapse"><i
                                class="fa fa-minus"></i>
                        </button>
                        <div class="btn-group">
                            <button type="button" class="btn btn-box-tool dropdown-toggle" data-toggle="dropdown">
                                <i class="fa fa-wrench"></i></button>
                            <ul class="dropdown-menu" role="menu">
                                <li><a href="#">{%trans 'Action' %}</a></li>
                                <li><a href="#">{%trans 'Another action' %}</a></li>
                                <li><a href="#">{%trans 'Something else here' %}</a></li>
                                <li class="divider"></li>
                                <li><a href="#">{%trans 'Separated link' %}</a></li>
                            </ul>
                        </div>
                        <button type="button" class="btn btn-box-tool" data-widget="remove"><i class="fa fa-times"></i>
                        </button>
                    </div>
                </div>
                <div class="box-body">

                    <div class="row">


                        <div class="col-lg-10">
                            <div class="content float-e-margins">
                                <div class="content">
                                    <form action="" class="form-horizontal nice-validator n-yellow form" method="post" novalidate="novalidate">
                                        {% csrf_token %}
                                        <p>{%trans 'Are you sure you want to delete user permission' %} "{{ object.user.username }}"?</p>
                                        <div class="col-sm-4 col-sm-offset-5">
                                            <button type="submit" id="submit" class="btn btn-primary pull-center">
                                                {%trans 'submit' %}
                                            </button>
                                        </div>

                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>

                </div>
            </div>
            <!-- END EXAMPLE TABLE PORTLET-->
        </div>

    </div>
</section>
{% endblock %}
{% block js %}
<script>
  $("[href='{% url 'permissionlist' %}']").parent("li").addClass('active')
</script>
{% endblock %}

permission/templates/permission/permissionupdate.html
{% extends 'base.html'%}
{%load i18n%}
{% block title %}{{ title }}{% endblock %}
{% load staticfiles %}
{% block css %}
<link rel="stylesheet" href="{% static 'plugins/select2/dist/css/select2.min.css' %}">
<link rel="stylesheet" href="{% static 'plugins/select2-bootstrap-theme/dist/select2-bootstrap.min.css' %}">
<link rel="stylesheet" href="{% static 'plugins/jstree/themes/proton/style.min.css' %}"/>
{% endblock %}
{% block content %}
{% load crispy_forms_tags %}
<section class="content">
    <div class="row">
        <div class="col-md-12">
            <!-- BEGIN EXAMPLE TABLE PORTLET-->
            <div class="box box-success">
                <div class="box-header with-border">
                    <div class="caption">
                        <button class="btn btn-primary" onclick="window.location.href = '{% url 'permissionlist' %}'">
                            {%trans 'Return Permission List' %}
                        </button>
                    </div>

                    <div class="box-tools pull-right">
                        <button type="button" class="btn btn-box-tool" data-widget="collapse"><i
                                class="fa fa-minus"></i>
                        </button>
                        <div class="btn-group">
                            <button type="button" class="btn btn-box-tool dropdown-toggle" data-toggle="dropdown">
                                <i class="fa fa-wrench"></i></button>
                            <ul class="dropdown-menu" role="menu">
                                <li><a href="#">{%trans 'Action' %}</a></li>
                                <li><a href="#">{%trans 'Another action' %}</a></li>
                                <li><a href="#">{%trans 'Something else here' %}</a></li>
                                <li class="divider"></li>
                                <li><a href="#">{%trans 'Separated link' %}</a></li>
                            </ul>
                        </div>
                        <button type="button" class="btn btn-box-tool" data-widget="remove"><i class="fa fa-times"></i>
                        </button>
                    </div>
                </div>

                <form id="id-m-form" action="" method="post" class="form form-horizontal " role="form">
                    <div class="box-body">
                        {% if form.helper %}
                            {% crispy form form.helper %}
                        {% else %}
                            {% crispy form %}
                        {% endif %}
                        <div class="form-group">
                            <div id="div_id_permissions_tree" class="form-group"><label for="div_id_permissions_tree"
                                                                            class="control-label col-md-2 requiredField">
                                {%trans 'Permissions' %}<span class="asteriskField">*</span> </label>
                                <div class="controls col-md-8">

                                 </div>
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-xs-offset-2 col-xs-10">
                                <button type="submit" class="btn btn-primary">{%trans 'submit' %}</button>
                                <button type="button" class="btn btn-default goback" onclick="history.back()">{%trans 'cancel' %}</button>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
            <!-- END EXAMPLE TABLE PORTLET-->
        </div>

    </div>
</section>
{% endblock %}
{% block js %}
<script type="text/javascript" src="{% static 'plugins/select2/dist/js/select2.full.min.js' %}"></script>
<script src="{% static 'plugins/jstree/jstree.js' %}"></script>
<script type="application/javascript">
    $('#id_groups,#id_user').select2({
        theme: "bootstrap"
    });
    //hide original permission tree
    $(".form-group[id='div_id_permissions']").hide()

    //generate new permission tree
    $("#div_id_permissions_tree >.col-md-8").jstree({
        core: {
            themes: {
                name: 'proton',
                // responsive: true
            },
            responsive: true,
            check_callback: 0,
            data: {{permission_tree_list|safe}},
        },
        types: {
            default: {icon: "fa fa-folder icon-state-warning icon-lg"},
            file: {icon: "fa fa-file icon-state-warning icon-lg"}
        },
        plugins: ["types","checkbox","state"],
        checkbox: {
            "tie_selection": false,
            "whole_node": false
        },
    }).on("check_node.jstree", function (e, data) {
            //update form data when select tree node
            if (data.node.original.level == "three"){
                $("input[value='"+data.node.original.id+"']").prop("checked",true)
            }else if (data.node.original.level == "two"){
                $(data.node.children).each(function (index,item) {
                    $("input[value='"+item+"']").prop("checked",true)
                })
            }else{
                $(data.node.children_d).each(function (index,item) {
                    $("input[value='"+item+"']").prop("checked",true)
                })
            }
        }).on("uncheck_node.jstree", function (e, data) {
        if (data.node.original.level == "three"){
            $("input[value='"+data.node.original.id+"']").prop("checked",false)
        }else if (data.node.original.level == "two"){
            $(data.node.children).each(function (index,item) {
                $("input[value='"+item+"']").prop("checked",false)
            })
        }else{
            $(data.node.children_d).each(function (index,item) {
                $("input[value='"+item+"']").prop("checked",false)
            })
        }
    }).on("loaded.jstree", function (event, data) {
        //initial tree data
        setTimeout(function () {
            $("#div_id_permissions_tree >.col-md-8").jstree(true).uncheck_all();
        },10)
        setTimeout(function () {
            $("#div_id_permissions_tree >.col-md-8 a").removeClass("jstree-clicked")
            $("#div_id_permissions >.col-md-8 .checkbox >label >input:checked").each(function (index, item) {
                // $('#div_id_permissions_tree >.col-md-8').jstree(true).select_node([$(this).val()])
                // $("#div_id_permissions_tree >.col-md-8 a[id='"+$(this).val()+"_anchor"+"']").addClass("jstree-checked")
                $("#div_id_permissions_tree >.col-md-8 a[id='"+$(this).val()+"_anchor"+"']"+" >i").trigger("click")
            });
        },100)
        setTimeout(function () {
            $("#div_id_permissions_tree >.col-md-8 a").removeClass("jstree-clicked")
        },350)
    });
</script>
<script>
  $("[href='{% url 'permissionlist' %}']").parent("li").addClass('active')
</script>

{% endblock %}